// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const pages: { "home": { "greeting": string; "tagline": string } };
  export const home: { "greeting": string; "tagline": string };
}
